# Generated by Django 5.2.8 on 2025-11-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SYSTEM_ADMIN', 'System Admin'), ('DEPARTMENT_ADMIN', 'Department Admin'), ('REVIEWER', 'Reviewer'), ('LECTURER', 'Lecturer'), ('STUDENT', 'Student')], max_length=20, null=True),
        ),
    ]
