# Generated by Django 5.2.8 on 2025-11-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='magic_link_sent',
            field=models.BooleanField(default=False),
        ),
    ]
