# Generated by Django 5.2.8 on 2025-11-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_signuprequest_magic_link_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
