# Generated by Django 5.2.8 on 2025-11-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_signuprequest_phone_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclink',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
