# Generated by Django 5.0.3 on 2025-11-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_magiclink_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='degree',
            field=models.CharField(choices=[('BSC', 'First degree (BSc)'), ('MSC', 'Second degree (MSc)'), ('BOTH', 'First & Second degree (BSc + MSc)')], default='BSC', max_length=20),
        ),
    ]
