# Generated by Django 5.2.8 on 2025-12-02 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_id_number_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='id_number',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='ID number must be exactly 9 digits.', regex='^\\d{9}$')]),
        ),
    ]
