# Generated by Django 5.2.8 on 2025-12-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_signuprequest_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependent_courses', to='api.course'),
        ),
    ]
