# Generated by Django 5.0.3 on 2025-12-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_course_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Reviewer Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=30),
        ),
    ]
