# Generated by Django 5.0.3 on 2025-12-22 11:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_syllabus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='content',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='academic_year',
            field=models.CharField(default='2025-2026', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='course_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='course_type',
            field=models.CharField(choices=[('MANDATORY', 'Mandatory'), ('ELECTIVE', 'Elective'), ('GENERAL', 'General')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='delivery',
            field=models.CharField(choices=[('IN_PERSON', 'In-person'), ('ZOOM', 'Zoom')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='guidelines',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='instructor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='language',
            field=models.CharField(default='Hebrew', max_length=50),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='learning_outputs',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='level',
            field=models.CharField(choices=[('BSC', 'BSc'), ('MSC', 'MSc')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='literature',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='purpose',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='teaching_methods_planned',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SyllabusAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('percent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='api.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('topic', models.TextField()),
                ('sources', models.TextField(blank=True, null=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='api.syllabus')),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
    ]
