# Generated by Django 5.0.3 on 2025-12-22 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_syllabus_content_syllabus_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='academic_year',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{4}$', 'academic_year must be like 2025-2026')]),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Reviewer Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='syllabus',
            constraint=models.UniqueConstraint(fields=('course', 'uploaded_by', 'academic_year'), name='unique_syllabus_per_course_per_year_per_lecturer'),
        ),
    ]
