# Generated by Django 5.0.3 on 2025-12-24 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_syllabus_academic_year_alter_syllabus_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='academic_year',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{4}$', 'academic_year must be like 2025-2026')]),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course_type',
            field=models.CharField(blank=True, choices=[('MANDATORY', 'Mandatory'), ('ELECTIVE', 'Elective'), ('GENERAL', 'General')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='delivery',
            field=models.CharField(blank=True, choices=[('IN_PERSON', 'In-person'), ('ZOOM', 'Zoom')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='guidelines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='language',
            field=models.CharField(blank=True, default='Hebrew', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='learning_outputs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='level',
            field=models.CharField(blank=True, choices=[('BSC', 'BSc'), ('MSC', 'MSc')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='literature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='teaching_methods_planned',
            field=models.TextField(blank=True, null=True),
        ),
    ]
