# Generated by Django 5.0.3 on 2025-12-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_syllabus_academic_year_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='syllabus',
            name='unique_syllabus_per_course_per_year_per_lecturer',
        ),
        migrations.AddConstraint(
            model_name='syllabus',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('course', 'uploaded_by', 'academic_year'), name='unique_syllabus_per_course_per_year_per_lecturer'),
        ),
        migrations.AddConstraint(
            model_name='syllabus',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING_REVIEW')), fields=('course', 'uploaded_by', 'academic_year'), name='unique_pending_per_course_year_lecturer'),
        ),
    ]
