# Generated by Django 5.0.3 on 2025-12-25 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_syllabus_unique_syllabus_per_course_per_year_per_lecturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='api.syllabus')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
