# Generated by Django 5.0.3 on 2025-12-25 10:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_syllabuschatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabusassessment',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='syllabuschatmessage',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='syllabusweek',
            name='syllabus',
        ),
        migrations.CreateModel(
            name='SyllabusDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{4}$', 'academic_year must be like 2025-2026')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_documents', to='api.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Reviewer Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('reviewer_comment', models.TextField(blank=True, null=True)),
                ('level', models.CharField(blank=True, choices=[('BSC', 'BSc'), ('MSC', 'MSc')], max_length=10, null=True)),
                ('course_type', models.CharField(blank=True, choices=[('MANDATORY', 'Mandatory'), ('ELECTIVE', 'Elective'), ('GENERAL', 'General')], max_length=20, null=True)),
                ('delivery', models.CharField(blank=True, choices=[('IN_PERSON', 'In-person'), ('ZOOM', 'Zoom')], max_length=20, null=True)),
                ('instructor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('language', models.CharField(blank=True, default='Hebrew', max_length=50, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('learning_outputs', models.TextField(blank=True, null=True)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('literature', models.TextField(blank=True, null=True)),
                ('teaching_methods_planned', models.TextField(blank=True, null=True)),
                ('guidelines', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.syllabusdocument')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='syllabusassessment',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='api.syllabusversion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabuschatmessage',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='api.syllabusversion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabusweek',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='api.syllabusversion'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='syllabusdocument',
            constraint=models.UniqueConstraint(fields=('course', 'lecturer', 'academic_year'), name='uniq_document_course_lecturer_year'),
        ),
        migrations.AddConstraint(
            model_name='syllabusversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='uniq_doc_version'),
        ),
        migrations.AddConstraint(
            model_name='syllabusversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('document',), name='uniq_draft_per_document'),
        ),
        migrations.AddConstraint(
            model_name='syllabusversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING_REVIEW')), fields=('document',), name='uniq_pending_per_document'),
        ),
    ]
