# Generated by Django 5.0.3 on 2025-12-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_syllabusassessment_syllabus_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='syllabus',
            name='unique_syllabus_per_course_per_year_per_lecturer',
        ),
        migrations.RemoveConstraint(
            model_name='syllabus',
            name='unique_pending_per_course_year_lecturer',
        ),
        migrations.RemoveField(
            model_name='syllabusassessment',
            name='version',
        ),
        migrations.RemoveField(
            model_name='syllabusweek',
            name='version',
        ),
        migrations.AddField(
            model_name='syllabusassessment',
            name='syllabus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='api.syllabus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabusweek',
            name='syllabus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='api.syllabus'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='syllabus',
            constraint=models.UniqueConstraint(fields=('course', 'uploaded_by', 'academic_year', 'version'), name='uniq_syllabus_course_lecturer_year_version'),
        ),
        migrations.AddConstraint(
            model_name='syllabus',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('course', 'uploaded_by', 'academic_year'), name='uniq_draft_per_course_lecturer_year'),
        ),
        migrations.AddConstraint(
            model_name='syllabus',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING_REVIEW')), fields=('course', 'uploaded_by', 'academic_year'), name='uniq_pending_per_course_lecturer_year'),
        ),
    ]
