# Generated by Django 5.0.3 on 2025-12-25 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_syllabus_unique_syllabus_per_course_per_year_per_lecturer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabusweek',
            options={},
        ),
        migrations.RemoveField(
            model_name='syllabuschatmessage',
            name='version',
        ),
        migrations.AddField(
            model_name='syllabuschatmessage',
            name='syllabus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='api.syllabus'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='syllabusweek',
            constraint=models.UniqueConstraint(fields=('syllabus', 'week_number'), name='uniq_week_per_syllabus'),
        ),
    ]
