# Generated by Django 5.2.1 on 2026-04-21 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_student_module_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='degree_track',
            field=models.CharField(choices=[('BSC', 'BSc'), ('MSC', 'MSc'), ('BOTH', 'BSc + MSc')], default='BSC', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='planning_type',
            field=models.CharField(choices=[('MANDATORY', 'Mandatory'), ('ELECTIVE', 'Elective')], default='MANDATORY', max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='bsc_max_counted_elective_credits',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='department',
            name='bsc_required_credits',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='department',
            name='msc_max_counted_elective_credits',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='department',
            name='msc_required_credits',
            field=models.PositiveIntegerField(default=36),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='degree_track',
            field=models.CharField(blank=True, choices=[('BSC', 'BSc'), ('MSC', 'MSc')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='degree_track',
            field=models.CharField(blank=True, choices=[('BSC', 'BSc'), ('MSC', 'MSc')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.CharField(choices=[('A', 'Semester A'), ('B', 'Semester B'), ('SUMMER', 'Summer Semester')], max_length=10)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-academic_year', 'semester'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'semester'), name='uniq_academic_term_year_semester'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='uniq_single_current_term')],
            },
        ),
        migrations.CreateModel(
            name='StudentSemesterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_track', models.CharField(choices=[('BSC', 'BSc'), ('MSC', 'MSc')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_plans', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_plans', to='api.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPlannedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_type', models.CharField(choices=[('MANDATORY', 'Mandatory'), ('ELECTIVE', 'Elective')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_in', to='api.course')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_courses', to='api.studentsemesterplan')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='api.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='api.department')),
                ('lecturers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'LECTURER'}, related_name='course_offerings', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='api.academicterm')),
            ],
            options={
                'ordering': ['course__code'],
                'constraints': [models.UniqueConstraint(fields=('course', 'term'), name='uniq_course_term_offering')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentsemesterplan',
            constraint=models.UniqueConstraint(fields=('student', 'term', 'degree_track'), name='uniq_student_term_degree_plan'),
        ),
        migrations.AddConstraint(
            model_name='studentplannedcourse',
            constraint=models.UniqueConstraint(fields=('plan', 'course'), name='uniq_plan_course'),
        ),
    ]
