# Generated by Django 5.2.1 on 2026-04-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_course_degree_track_course_planning_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lecturers',
        ),
        migrations.AddField(
            model_name='studentplannedcourse',
            name='counts_toward_degree_elective',
            field=models.BooleanField(default=True),
        ),
    ]
