# Generated by Django 5.2.1 on 2026-04-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_course_lecturers_planned_elective_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='student_edit_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='student_edit_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
