# Generated by Django 5.2.1 on 2026-04-23 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_offering_student_window_year_caps'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTermEditWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_edit_start', models.DateTimeField(blank=True, null=True)),
                ('student_edit_end', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_edit_windows', to='api.department')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_edit_windows', to='api.academicterm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('department', 'term'), name='uniq_department_term_edit_window')],
            },
        ),
    ]
